//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A_Song_of_Ice_and_Fire.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ASOIAF
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Name is Required")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Allegiance is Required")]
        public string Allegiance { get; set; }
        public string Alias { get; set; }
        public string Image { get; set; }
        public string Profile { get; set; }

        [Required(ErrorMessage = "Status is Required")]
        public string Are_They_Dead_ { get; set; }
    }
}
